version: '2.4'

services:
  dynamodb:
    image: amazon/dynamodb-local:1.15.0
    container_name: dynamodb-local
    volumes:
      - ./volumes/dynamodb:/data
    command: [ "-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/data" ]
    ports:
      - "8000:8000"
  aws-cli:
    image: amazon/aws-cli:2.1.28
    container_name: aws-cli
    depends_on:
      - dynamodb
    command: "aws dynamodb create-table --endpoint-url http://localhost:8000 --region sa-east-1 --table-name tb_product --attribute-definitions AttributeName=id,AttributeType=S --key-schema AttributeName=id,KeyType=HASH --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5"
